# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 12:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('var1', models.TextField()),
                ('sub_topic', models.TextField()),
                ('var2', models.TextField()),
                ('short', models.TextField()),
                ('possible', models.TextField()),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('image', models.TextField()),
                ('ck', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
